/* ================================================ */
/*  lang.js — AzerHistory 3D  Ortaq dil sistemi     */
/*  (nav, footer, hero, about, lobi, zal başlıqları) */
/* ================================================ */

const T = {
    az: {
        // ---- NAVBAR / ÜMUMI ----
        nav_home: "Ana Səhifə",
        nav_about: "Haqqımızda",
        nav_lobby: "Muzey Lobisi",
        nav_timeline: "Zaman Xətti",
        back_to_lobby: "Lobiyə qayıt",
        music: "Musiqi",

        // ---- AUTH MODAL ----
        auth_login_title: "Giriş Et",
        auth_signup_title: "Qeydiyyatdan Keç",
        auth_sub: "AzerHistory 3D-yə xoş gəlmisiniz",
        auth_email: "Email",
        auth_password: "Şifrə",
        auth_login_btn: "Giriş Et",
        auth_signup_btn: "Qeydiyyatdan Keç",
        auth_toggle_to_signup: "Hesabın yoxdur? Qeydiyyatdan keç",
        auth_fullname: "Ad Soyad",
        auth_country: "Ölkə",
        auth_toggle_to_login: "Artıq hesabın var? Giriş et",

        // ---- ANA SƏHİFƏ (FLL.html) HERO ----
        hero_badge: "🏛️ Rəqəmsal Muzey",
        hero_title1: "Milli İrsin",
        hero_title2: "Rəqəmsal Arxivi",
        hero_sub: "Minilliklərin mirasını müasir texnologiya ilə kəşf edin. Hər bir artefakt xalqımızın keçmişinə açılan bir pəncərədir.",
        hero_btn: "Muzeyə Gir",
        hero_btn2: "Zaman Xətti",
        stat1: "Eksponat",
        stat2: "İl Tarix",
        stat3: "3D Model",
        scroll: "Aşağı sürüşdür",

        // ---- HAQQIMIZDA (about) ----
        about_eyebrow: "| HAQQIMIZDA",
        about_title: "AzerHistory 3D Nədir?",
        about_p1: "AzerHistory 3D — Azərbaycanın minillik tarixini rəqəmsal dünyaya daşıyan onlayn muzeydir. Kitabdan oxumaq əvəzinə, hər bir artefaktı öz gözünlə görə, sikkələri və qədim əşyaları 360° döndərə, tarixi abidələri yaxından tanıya bilərsən.",
        about_p2: "Muzeyimiz beş ayrı zaldan ibarətdir — hər biri fərqli bir dövrü və fərqli bir hekayəni gəzdirir: insanlığın ilk izlərindən tutmuş, qədim dövlətlərin qızıl sənətkarlığına, daşa yazılmış memarlıq möcüzələrinə qədər. Zaman Xətti isə səni 400,000 il əvvəldən bu günə qədər aparan bir yolçuluğa çıxarır.",
        about_p3: "Qeydiyyatdan keçib hər eksponata öz fikrini yaza, başqalarının rəylərini oxuya bilərsən. Məqsədimiz sadədir: keçmişi bugünün dili ilə danışdırmaq.",
        about_btn: "Muzeyi Gəz",
        about_stat1: "Muzey Zalı",
        about_stat2: "Eksponat",
        about_stat3: "İl Tarix",
        about_stat4: "3D Model",

        // ---- LOBİ ----
        lobby_badge: "🏛️ Rəqəmsal Muzey — Ana Lobi",
        lobby_h1_1: "Xoş gəlmisiniz.",
        lobby_h1_2: "Hansı zaldan başlayaq?",
        lobby_p: "Hər zal ayrı bir dövrü, ayrı bir hekayəni gəzdirir. İstədiyin zaldan başla, istənilən vaxt bu lobiyə qayıt.",
        hall1_title: "Paleontologiya",
        hall1_desc: "İnsanlığın ilk izləri — 400,000 il əvvələ gedən yol.",
        hall2_title: "Numizmatika & 3D Arxiv",
        hall2_desc: "Sikkələr, dulusçuluq — əlində tutub 360° döndərə biləcəyin əşyalar.",
        hall3_title: "Arxeoloji Tapıntılar",
        hall3_desc: "Qızıl bəzəklər, silahlar, qaya rəsmləri — torpağın dərinliyindən çıxanlar.",
        hall4_title: "Memarlıq Abidələri",
        hall4_desc: "Qız Qalası, Şəki Sarayı, Atəşgah — daşa yazılmış tariximiz.",
        hall5_title: "Zaman Xətti",
        hall5_desc: "400,000 il əvvəldən bu günə — bir yol boyu bütün tarix.",
        eksponat_word: "eksponat",

        // ---- ZAL SƏHİFƏ BAŞLIQLARI ----
        hall1_page_title1: "Paleontologiya",
        hall1_page_title2: "Zalı",
        hall1_page_sub: "Bəşəriyyətin Azərbaycan torpağındakı ən qədim izləri — daşlaşmış sümüklərin danışdığı hekayə.",
        hall2_page_title1: "Numizmatika",
        hall2_page_title2: "& 3D Arxiv",
        hall2_page_sub: "Əlində tutub 360° döndərə biləcəyin əşyalar — sikkələr və qablar, minilliklər öncədən qalma.",
        hall3_page_title1: "Arxeoloji",
        hall3_page_title2: "Tapıntılar",
        hall3_page_sub: "Torpağın dərinliyindən çıxan qızıl bəzəklər, silahlar və qaya rəsmləri — doqquz min illik səyahət.",
        hall4_page_title1: "Memarlıq",
        hall4_page_title2: "Abidələri",
        hall4_page_sub: "Daşa, taxtaya və tuncə həkk olunmuş tarix — saraylar, türbələr, qalalar və məbədlər.",

        // ---- FOOTER ----
        footer_copy: "© 2026 AzerHistory 3D",
        cene_tag: "Paleoantropologiya",
        cene_title: "Azıxantropun Çənə Sümüyü",
        cene_f1l: "Yaş:",
        cene_f1v: "350,000–400,000 il",
        cene_f2l: "Tapıldığı yer:",
        cene_f2v: "Azıx mağarası, Qazax",
        cene_f3l: "Növ:",
        cene_f3v: "Pre-neandertal",
        cene_desc: "1968-ci ildə Məmmədəli Hüseynov tərəfindən aşkar edilən bu çənə sümüyü dünya antropologiya elmini dəyişdi. Dünyada tapılan ən qədim insan qalıqlarından dördüncüsüdür.",
        cene_ctxh: "Antropoloji Əhəmiyyət",
        cene_ctxp: "Bu tapıntı Azərbaycanın bəşəriyyətin ilk formalaşdığı ocaqlardan biri olduğunu təsdiqləyir.",
        taglar_tag: "Paleolit Alətlər",
        taglar_title: "Tağlar Mağarası Alətləri",
        taglar_f1l: "Dövr:",
        taglar_f1v: "Orta Paleolit (Mustye mədəniyyəti)",
        taglar_f2l: "Material:",
        taglar_f2v: "Çaxmaqdaşı",
        taglar_f3l: "Məkan:",
        taglar_f3v: "Tağlar mağarası, Füzuli rayonu",
        taglar_desc: "Tağlar mağarası Azıxdan sonra Qarabağda aşkarlanan ən mühüm paleolit yaşayış yeridir. Burada tapılan çaxmaqdaşı alətlər — qaşovlar, kəsicilər, ucluqlar — neandertal insanın ovçuluq və emal texnikasını göstərir.",
        taglar_ctxh: "Mustye Mədəniyyəti",
        taglar_ctxp: "Bu alətlər Azıxantropdan sonrakı nəslin, klassik Neandertal insanının Qarabağda məskunlaşdığını sübut edir.",
        damcili_tag: "Mezolit Dövrü",
        damcili_title: "Damcılı Mağarası Tapıntıları",
        damcili_f1l: "Dövr:",
        damcili_f1v: "Mezolit (e.ə. X–VIII minillik)",
        damcili_f2l: "Material:",
        damcili_f2v: "Sümük, daş",
        damcili_f3l: "Məkan:",
        damcili_f3v: "Damcılı mağarası, Qazax rayonu",
        damcili_desc: "Damcılı mağarasında aşkarlanan mikrolit alətlər və sümük məmulatları Mezolit dövründə insanın ovçuluqdan tədricən əkinçilik və maldarlığa keçidini əks etdirir.",
        damcili_ctxh: "Keçid Dövrü",
        damcili_ctxp: "Damcılı tapıntıları Azərbaycanda \"Neolit inqilabı\"na gedən yolun ilk addımlarından xəbər verir.",
        azixfauna_tag: "Paleozoologiya",
        azixfauna_title: "Azıx Mağarasının Fauna Qalıqları",
        azixfauna_f1l: "Dövr:",
        azixfauna_f1v: "400,000–350,000 il əvvəl",
        azixfauna_f2l: "Material:",
        azixfauna_f2v: "Sümük qalıqları",
        azixfauna_f3l: "Məkan:",
        azixfauna_f3v: "Azıx mağarası, Füzuli rayonu",
        azixfauna_desc: "Azıxantropla eyni təbəqələrdə aşkarlanan mağara ayısı, bizon və maral sümükləri, qədim insanın hansı heyvanları ovladığını və mağaranı necə istifadə etdiyini göstərir.",
        azixfauna_ctxh: "Ekoloji Şahid",
        azixfauna_ctxp: "Bu qalıqlar 400 min il əvvəl Qarabağın iqlimi və heyvanat aləmi haqqında elmə əvəzsiz məlumat verir.",
        sikke_tag: "Numizmatika",
        sikke_title: "Qədim Azərbaycan Sikkəsi",
        sikke_f1l: "Dövr:",
        sikke_f1v: "7-10-cu əsrlər",
        sikke_f2l: "Material:",
        sikke_f2v: "Gümüş Dirhəm",
        sikke_f3l: "Çəki:",
        sikke_f3v: "~2.8 qr",
        sikke_desc: "Bu sikkə orta əsrlərdə Azərbaycan ərazisindəki dövlətlərin iqtisadi müstəqilliyini nümayiş etdirir. Kufi xətti ilə yazılmış kitabə dövrün xəlifəsinin adını göstərir.",
        sikke_ctxh: "Niyə mühümdür?",
        sikke_ctxp: "Sikkə zərb etmək dövlətçilik rəmzi idi. Bu artefakt o dövrün ticarət sistemi haqqında məlumat verir.",
        dulus_tag: "Arxeologiya",
        dulus_title: "Ordubad Tunc Artefaktı",
        dulus_f1l: "Məkan:",
        dulus_f1v: "Naxçıvan MR",
        dulus_f2l: "Dövr:",
        dulus_f2v: "Tunc Dövrü (e.ə. II min.)",
        dulus_f3l: "Mədəniyyət:",
        dulus_f3v: "Boyalı Qablar",
        dulus_desc: "Ordubad ətrafında aparılan qazıntılarda tapılan bu artefakt qədim Naxçıvan tayfalarının yüksək sənətkarlıq bacarıqlarını göstərir.",
        dulus_ctxh: "Bölgənin Tarixi",
        dulus_ctxp: "Naxçıvan qədim Azərbaycan dövlətçiliyinin ən qədim mərkəzlərindən hesab olunur.",
        sasani_tag: "Numizmatika",
        sasani_title: "Sasani Dirhəmi",
        sasani_f1l: "Dövr:",
        sasani_f1v: "VI əsr (Sasani imperiyası)",
        sasani_f2l: "Material:",
        sasani_f2v: "Gümüş",
        sasani_f3l: "Məkan:",
        sasani_f3v: "Azərbaycan ərazisi (Sasani əyaləti)",
        sasani_desc: "İslamaqədərki dövrün pul dövriyyəsini əks etdirən bu dirhəm, Sasani şahənşahının portreti və atəşgah simvolu ilə zərb olunub. Ərəb fəthindən əvvəl Azərbaycanın Sasani imperiyasının bir əyaləti olduğunu göstərir.",
        sasani_ctxh: "Sələf Sikkə",
        sasani_ctxp: "Sonrakı ərəb dirhəmlərinin çəki və forma standartı məhz bu Sasani sikkələrindən götürülüb.",
        shirvansikke_tag: "Numizmatika",
        shirvansikke_title: "Şirvanşahlar Sikkəsi",
        shirvansikke_f1l: "Dövr:",
        shirvansikke_f1v: "XII–XV əsr",
        shirvansikke_f2l: "Material:",
        shirvansikke_f2v: "Gümüş/mis",
        shirvansikke_f3l: "Məkan:",
        shirvansikke_f3v: "Şamaxı, Bakı (Şirvanşahlar dövləti)",
        shirvansikke_desc: "Şirvanşahlar sülaləsinin zərb etdiyi bu sikkələr üzərində hökmdarın adı və dövrün kəlmeyi-şəhadəti həkk olunub. Dövlətin təxminən 800 il davam edən varlığının iqtisadi sübutlarından biridir.",
        shirvansikke_ctxh: "Uzunömürlü Sülalə",
        shirvansikke_ctxp: "Şirvanşahlar Azərbaycan tarixinin ən uzun hakimiyyət sürən sülaləsi olub, bu sikkələr onların hər dövründən iz daşıyır.",
        eldeniz_tag: "Numizmatika",
        eldeniz_title: "Eldənizlər Dövrü Sikkəsi",
        eldeniz_f1l: "Dövr:",
        eldeniz_f1v: "XII əsr",
        eldeniz_f2l: "Material:",
        eldeniz_f2v: "Mis (fəls)",
        eldeniz_f3l: "Məkan:",
        eldeniz_f3v: "Gəncə, Naxçıvan (Atabəylər dövləti)",
        eldeniz_desc: "Azərbaycan Atabəyləri (Eldənizlər) dövlətinin zərb etdiyi bu sikkə, Nizami Gəncəvinin yaşadığı dövrün iqtisadi həyatından bir parçadır. Səlcuq ənənələrini davam etdirən həndəsi naxışlarla bəzədilib.",
        eldeniz_ctxh: "Ədəbi Qızıl Dövr",
        eldeniz_ctxp: "Bu sikkənin zərb olunduğu dövrdə Gəncədə Nizami Gəncəvi əsərlərini yazırdı — Zal 4-dəki Möminə Xatun türbəsi də elə bu dövrün abidəsidir.",
        at_tag: "Arxeologiya",
        at_title: "Qədim At Fiquru",
        at_f1l: "Dövr:",
        at_f1v: "e.ə. I minillik",
        at_f2l: "Material:",
        at_f2v: "Tunc",
        at_f3l: "Məkan:",
        at_f3v: "Mil-Qarabağ düzü",
        at_desc: "Qədim dövrə aid tunc at heykəlciyidir. At qədim Azərbaycan mədəniyyətində güc və azadlıq simvolu idi.",
        at_ctxh: "Simvolik Əhəmiyyət",
        at_ctxp: "At fiqurları çox vaxt hökmdar məzarlarında tapılır — ruhun o dünyaya süvari getməsini simvolizə edir.",
        bicak_tag: "Tunc Dövrü",
        bicak_title: "Tunc Dövrünə Aid Silahlar",
        bicak_f1l: "Dövr:",
        bicak_f1v: "e.ə. II–I minillik",
        bicak_f2l: "Material:",
        bicak_f2v: "Tunc",
        bicak_f3l: "Məkan:",
        bicak_f3v: "Gəncə-Qazax bölgəsi",
        bicak_desc: "Xəncər, nizə ucluğu və ox ucluğundan ibarət bu toplu döyüş və ov üçün istifadə olunurdu.",
        bicak_ctxh: "Sənətkarlıq",
        bicak_ctxp: "Bu silahların forması Ön Asiya döyüş ənənəsinin Azərbaycanda unikal inkişafını göstərir.",
        manna_tag: "Manna Dövləti",
        manna_title: "Manna Dövrü Qızıl Əşyaları",
        manna_f1l: "Dövr:",
        manna_f1v: "e.ə. IX–VII əsr",
        manna_f2l: "Material:",
        manna_f2v: "Qızıl",
        manna_f3l: "Məkan:",
        manna_f3v: "Cənubi Azərbaycan",
        manna_desc: "Bu qızıl bəzək toplusu — boyunbağı, bilərziklər, sırğalar — Manna dövlətinin zərif sənətkarlığının şahididir.",
        manna_ctxh: "Dövlətçilik",
        manna_ctxp: "Manna Azərbaycanın ən qədim dövlətlərindəndir. Assuriya mənbələrindən məlumdur.",
        gamigaya_tag: "Petroqlif",
        gamigaya_title: "Gəmiqaya Petroqlifləri",
        gamigaya_f1l: "Dövr:",
        gamigaya_f1v: "e.ə. IV–I minillik",
        gamigaya_f2l: "Məkan:",
        gamigaya_f2v: "Ordubad, Naxçıvan",
        gamigaya_f3l: "Növ:",
        gamigaya_f3v: "Qaya rəsmləri",
        gamigaya_desc: "Gəmiqaya dağlarında minlərlə qədim qaya rəsmi tapılmışdır — heyvan, insan və astral simvollar təsvir olunur.",
        gamigaya_ctxh: "Elmi Əhəmiyyət",
        gamigaya_ctxp: "Gəmiqaya rəsmləri qədim insanların dünyagörüşünü, təsərrüfat həyatını əks etdirən nadir mənbədir.",
        qobustan_tag: "Petroqlif",
        qobustan_title: "Qobustan Qaya Rəsmləri",
        qobustan_f1l: "Dövr:",
        qobustan_f1v: "Paleolit – Orta əsr",
        qobustan_f2l: "Məkan:",
        qobustan_f2v: "Qobustan Milli Parkı",
        qobustan_f3l: "Say:",
        qobustan_f3v: "6000+ rəsm",
        qobustan_desc: "Qobustan Milli Parkında minlərlə il əvvəldən qalma qaya rəsmləri — ov səhnələri, rəqs edən insanlar, qayıqlar təsvir olunur.",
        qobustan_ctxh: "YUNESKO İrsi",
        qobustan_ctxp: "Qobustan 2007-ci ildə YUNESKO-nun Ümumdünya İrs siyahısına daxil edilib.",
        xinisli_tag: "Arxeologiya",
        xinisli_title: "Xınıslı Nekropolü",
        xinisli_f1l: "Dövr:",
        xinisli_f1v: "e.ə. VIII–IV əsr",
        xinisli_f2l: "Məkan:",
        xinisli_f2v: "Xınıslı, Bakı ətrafı",
        xinisli_f3l: "Növ:",
        xinisli_f3v: "Skif dövrü nekropolü",
        xinisli_desc: "Xınıslı nekropolündə aparılan qazıntılarda qızıl bəzəklər, silahlar, at avadanlıqları və keramika tapılmışdır.",
        xinisli_ctxh: "Tarixi Kontekst",
        xinisli_ctxp: "Xınıslı nekropolü Albaniya öncəsi dövr üçün ən zəngin arxeoloji mənbələrdən biridir.",
        mingecevir_tag: "Albaniya Dövrü",
        mingecevir_title: "Mingəçevir Nekropolü Tapıntıları",
        mingecevir_f1l: "Dövr:",
        mingecevir_f1v: "e.ə. I əsr – e. VIII əsr",
        mingecevir_f2l: "Məkan:",
        mingecevir_f2v: "Mingəçevir, Kür sahili",
        mingecevir_f3l: "Tapıntı növü:",
        mingecevir_f3v: "Küp qəbirləri, keramika, zinət",
        mingecevir_desc: "Mingəçevir nekropolündə aparılan qazıntılar Qafqaz Albaniyasının ən zəngin arxeoloji materiallarını üzə çıxarmışdır.",
        mingecevir_ctxh: "Arxeoloji Əhəmiyyət",
        mingecevir_ctxp: "Mingəçevir tapıntıları Qafqaz Albaniyasının mədəni müxtəlifliyini sübut edir.",
        skif_tag: "Skif Dövrü",
        skif_title: "Skif Kurqanı Tapıntıları",
        skif_f1l: "Dövr:",
        skif_f1v: "e.ə. VII–IV əsr",
        skif_f2l: "Məkan:",
        skif_f2v: "Mil düzü, Ağcabədi",
        skif_f3l: "Material:",
        skif_f3v: "Qızıl, tunc, dəmir",
        skif_desc: "Mil düzündə tapılan Skif kurqanlarından əldə edilmiş qızıl bəzəklər Skif tayfalarının Azərbaycan ərazisindəki mövcudluğunu sübut edir.",
        skif_ctxh: "Tarix Konteksti",
        skif_ctxp: "Skiflər e.ə. VII əsrdə Cənubi Qafqaza gəlmiş köçəri xalq idi.",
        qala_tag: "Orta Əsrlər",
        qala_title: "Qala Arxeoloji-Etnoqrafik Kompleksi",
        qala_f1l: "Dövr:",
        qala_f1v: "Erkən orta əsrlər – XIX əsr",
        qala_f2l: "Məkan:",
        qala_f2v: "Qala kəndi, Abşeron",
        qala_f3l: "Status:",
        qala_f3v: "Dövlət Muzey Qoruğu",
        qala_desc: "Abşeron yarımadasında yerləşən Qala kəndinin arxeoloji qazıntıları zamanı 2000-dən çox artefakt tapılmışdır.",
        qala_ctxh: "Mədəni İrs",
        qala_ctxp: "Qala kompleksi Abşeronun arxeoloji, etnoqrafik və memarlıq irsini bir arada qoruyub saxlayan nadir muzey-qoruqlardandır.",
        shirvan_tag: "Orta Əsrlər",
        shirvan_title: "Şirvanşahlar Sarayı",
        shirvan_f1l: "Dövr:",
        shirvan_f1v: "XV əsr",
        shirvan_f2l: "Məkan:",
        shirvan_f2v: "İçərişəhər, Bakı",
        shirvan_f3l: "Status:",
        shirvan_f3v: "YUNESKO abidəsi",
        shirvan_desc: "Şirvanşahlar sarayı Azərbaycan memarlığının incisidir. Kompleksdə saray, məscid, türbə və hamam yerləşir.",
        shirvan_ctxh: "Memarlıq İrsi",
        shirvan_ctxp: "Kompleks 2000-ci ildə YUNESKO-nun Ümumdünya İrs siyahısına daxil edilib.",
        qizqalasi_tag: "Memarlıq Abidəsi",
        qizqalasi_title: "Qız Qalası",
        qizqalasi_f1l: "Dövr:",
        qizqalasi_f1v: "XII əsr (alt qatlar daha qədim)",
        qizqalasi_f2l: "Məkan:",
        qizqalasi_f2v: "İçərişəhər, Bakı",
        qizqalasi_f3l: "Status:",
        qizqalasi_f3v: "YUNESKO Ümumdünya İrsi",
        qizqalasi_desc: "Qız Qalası Azərbaycanın ən tanınan simvoludur — 8 mərtəbəli, silindrik formalı, 29 metr hündürlüyündə qala. Tikilmə tarixi və məqsədi haqqında hələ də mübahisələr davam edir: bəzi tədqiqatçılar onu müdafiə istehkamı, bəziləri isə zərdüştlük məbədi hesab edir. Qalanın adı ilə bağlı bir neçə əfsanə yaşayır — ən məşhuru, atası tərəfindən zorla evləndirilmək istənən şahzadə qızın qaladan Xəzərə atılması hekayəsidir.",
        qizqalasi_ctxh: "Memarlıq Siri",
        qizqalasi_ctxp: "Qalanın divarlarındakı sirli çıxıntı və divar qalınlığının məqsədi bu günə qədər tam izah edilə bilməyib — bu da onu Şərqin ən müəmmalı abidələrindən birinə çevirir.",
        sheki_tag: "Saray Memarlığı",
        sheki_title: "Şəki Xan Sarayı",
        sheki_f1l: "Dövr:",
        sheki_f1v: "XVIII əsr",
        sheki_f2l: "Məkan:",
        sheki_f2v: "Şəki şəhəri",
        sheki_f3l: "Xüsusiyyət:",
        sheki_f3v: "Şəbəkə pəncərələri, divar rəsmləri",
        sheki_desc: "Şəki xanlarının yay iqamətgahı kimi tikilən bu saray, bir mismar belə istifadə edilmədən yığılıb — taxta hissələr yalnız oyma və keçidlərlə bir-birinə bağlanıb. Şəbəkə pəncərələri rəngli şüşə qırıqlarından düzəldilib, günəş işığı düşəndə otaq içi min bir rəngə boyanır. Divarlardakı freskalar ov səhnələri və çiçək naxışları ilə zəngindir.",
        sheki_ctxh: "Sənətkarlıq Möcüzəsi",
        sheki_ctxp: "Bir şəbəkə pəncərəsi hazırlamaq üçün ustalar aylarla işləyirdi — bu texnika bu gün demək olar ki, unudulmaq üzrədir.",
        momune_tag: "Türbə Memarlığı",
        momune_title: "Möminə Xatun Türbəsi",
        momune_f1l: "Dövr:",
        momune_f1v: "1186-cı il",
        momune_f2l: "Memar:",
        momune_f2v: "Əcəmi Naxçıvani",
        momune_f3l: "Məkan:",
        momune_f3v: "Naxçıvan şəhəri",
        momune_desc: "Naxçıvan memarlıq məktəbinin banisi Əcəmi Əbubəkr oğlu Naxçıvaninin ən möhtəşəm əsəri. On üzlü prizma formasında olan bu türbə, səthini örtən həndəsi və epiqrafik naxışlarla Şərq memarlığının zirvəsi hesab olunur. Atabəy Şəmsəddin Eldənizin arvadı Möminə Xatunun xatirəsinə tikilib.",
        momune_ctxh: "Naxçıvan Memarlıq Məktəbi",
        momune_ctxp: "Əcəminin işlətdiyi həndəsi naxış üsulları sonrakı əsrlərdə bütün Yaxın Şərq memarlığına təsir göstərib.",
        ateshgah_tag: "Zərdüştlük İbadətgahı",
        ateshgah_title: "Atəşgah Məbədi",
        ateshgah_f1l: "Dövr:",
        ateshgah_f1v: "XVII–XVIII əsr",
        ateshgah_f2l: "Məkan:",
        ateshgah_f2v: "Sürəxanı, Bakı",
        ateshgah_f3l: "Banisi:",
        ateshgah_f3v: "Hind tacirləri",
        ateshgah_desc: "Yerin təkindən çıxan təbii qazın əsrlər boyu sönmədən yanması bu yeri müqəddəs ziyarətgaha çevirib. Beşbucaqlı qala divarları içərisindəki mərkəzi məbəd hind tacirləri tərəfindən tikilib və zərdüştlərin, hindusların, sikhlərin ortaq ibadət yeri olub. Divarlarda sanskrit və pəncabi dillərində yazılar qalır.",
        ateshgah_ctxh: "Sönməyən Alov",
        ateshgah_ctxp: "XX əsrdə neft-qaz sənayesi inkişaf edəndə təbii qaz tükənib, indi \"əbədi alov\" süni qazla dəstəklənir.",
        gencegapilari_tag: "Tunc Tökmə Sənəti",
        gencegapilari_title: "Gəncə Qapıları",
        gencegapilari_f1l: "Hazırlanma:",
        gencegapilari_f1v: "1063-cü il",
        gencegapilari_f2l: "Material:",
        gencegapilari_f2v: "Tunc",
        gencegapilari_f3l: "Hazırkı yer:",
        gencegapilari_f3v: "Gelati monastırı, Gürcüstan",
        gencegapilari_desc: "Gəncə şəhərinin darvazaları üçün tökülmüş bu möhtəşəm tunc qapılar orta əsr metaltökmə sənətinin nadir nümunəsidir. 1139-cu ildə güclü zəlzələdən sonra şəhər dağılanda, sonra isə 1804-cü ildə rus qoşunları Gəncəni işğal edərkən qapılar qənimət kimi aparılıb və bu gün Gürcüstandakı Gelati monastırında saxlanılır.",
        gencegapilari_ctxh: "Qaytarılmayan İrs",
        gencegapilari_ctxp: "Qapılar üzərindəki ərəb yazıları onların Gəncədə hazırlandığını dəqiq təsdiqləyir — bu, itirilmiş mədəni irsin ən çarpıcı nümunələrindən biridir.",
        footer_credit: "Məhəmməd Hüseynov tərəfindən yaradılıb",
        footer_home: "Ana Səhifəyə Qayıt",
        hall_word: "ZAL",
        pause: "Dayandır",
        auth_btn: "Giriş",
        auth_wait: "Gözləyin...",
        auth_signup_ok: "✅ Qeydiyyat uğurludur! Emailinizi yoxlayın və linkə klik edin.",
        err_invalid: "❌ Email və ya şifrə yanlışdır",
        err_unconfirmed: "❌ Zəhmət olmasa emailinizi təsdiqləyin",
        err_exists: "❌ Bu email artıq qeydiyyatdan keçib",
        err_password: "❌ Şifrə ən azı 6 simvol olmalıdır",
        badge_gem: "★ Zalın İncisi",
        badge_flagship: "★ Flaqman Eksponat",
        badge_symbol: "★ Milli Rəmz",
        count_exhibit: "eksponat",
        count_finds: "tapıntı",
        count_monuments: "abidə",
        count_events: "hadisə",
        comments_title: "Şərhlər",
        comment_placeholder: "Fikrini yaz...",
        comment_send: "Göndər",
        comments_loading: "Şərhlər yüklənir...",
        comments_empty: "Hələ şərh yoxdur. İlk şərhi sən yaz!",
        comments_error: "Şərhlər yüklənə bilmədi.",
        comment_login_alert: "Şərh yazmaq üçün əvvəlcə giriş edin!",
        comment_confirm_delete: "Şərhi silmək istədiyinizə əminsiniz?",
        comment_send_fail: "Şərh göndərilə bilmədi: ",
        user_default: "İstifadəçi",
    },
    en: {
        nav_home: "Home",
        nav_about: "About",
        nav_lobby: "Museum Lobby",
        nav_timeline: "Timeline",
        back_to_lobby: "Back to lobby",
        music: "Music",

        auth_login_title: "Log In",
        auth_signup_title: "Sign Up",
        auth_sub: "Welcome to AzerHistory 3D",
        auth_email: "Email",
        auth_password: "Password",
        auth_login_btn: "Log In",
        auth_signup_btn: "Sign Up",
        auth_toggle_to_signup: "No account? Sign up",
        auth_fullname: "Full Name",
        auth_country: "Country",
        auth_toggle_to_login: "Already have an account? Log in",

        hero_badge: "🏛️ Digital Museum",
        hero_title1: "National Heritage",
        hero_title2: "Digital Archive",
        hero_sub: "Discover millennia of heritage through modern technology. Every artifact is a window into our people's past.",
        hero_btn: "Enter the Museum",
        hero_btn2: "Timeline",
        stat1: "Exhibits",
        stat2: "Years of History",
        stat3: "3D Models",
        scroll: "Scroll down",

        about_eyebrow: "| ABOUT",
        about_title: "What is AzerHistory 3D?",
        about_p1: "AzerHistory 3D is an online museum bringing Azerbaijan's millennia-old history into the digital world. Instead of reading from a book, you can see every artifact with your own eyes, rotate coins and ancient objects in 360°, and get up close to historic monuments.",
        about_p2: "Our museum has five separate halls — each carrying a different era and a different story: from humanity's earliest traces, to the gold craftsmanship of ancient states, to architectural wonders carved in stone. The Timeline takes you on a journey from 400,000 years ago to today.",
        about_p3: "Sign up to write your own thoughts on each exhibit and read others' comments. Our goal is simple: to let the past speak in today's language.",
        about_btn: "Explore the Museum",
        about_stat1: "Museum Halls",
        about_stat2: "Exhibits",
        about_stat3: "Years of History",
        about_stat4: "3D Models",

        lobby_badge: "🏛️ Digital Museum — Main Lobby",
        lobby_h1_1: "Welcome.",
        lobby_h1_2: "Which hall shall we start with?",
        lobby_p: "Each hall carries a different era, a different story. Start with any hall, and return to this lobby anytime.",
        hall1_title: "Paleontology",
        hall1_desc: "Humanity's first traces — a road stretching back 400,000 years.",
        hall2_title: "Numismatics & 3D Archive",
        hall2_desc: "Coins, pottery — objects you can hold and rotate 360° in your hand.",
        hall3_title: "Archaeological Finds",
        hall3_desc: "Gold ornaments, weapons, rock art — things risen from the depths of the earth.",
        hall4_title: "Architectural Monuments",
        hall4_desc: "Maiden Tower, Sheki Palace, Ateshgah — our history carved in stone.",
        hall5_title: "Timeline",
        hall5_desc: "From 400,000 years ago to today — the whole of history along one path.",
        eksponat_word: "exhibits",

        hall1_page_title1: "Paleontology",
        hall1_page_title2: "Hall",
        hall1_page_sub: "Humanity's oldest traces on Azerbaijani soil — the story fossilized bones tell.",
        hall2_page_title1: "Numismatics",
        hall2_page_title2: "& 3D Archive",
        hall2_page_sub: "Objects you can hold and rotate 360° in your hand — coins and vessels from millennia ago.",
        hall3_page_title1: "Archaeological",
        hall3_page_title2: "Finds",
        hall3_page_sub: "Gold ornaments, weapons and rock art risen from the depths of the earth — a nine-thousand-year journey.",
        hall4_page_title1: "Architectural",
        hall4_page_title2: "Monuments",
        hall4_page_sub: "History carved into stone, wood and bronze — palaces, mausoleums, fortresses and temples.",

        footer_copy: "© 2026 AzerHistory 3D",
        cene_tag: "Paleoanthropology",
        cene_title: "Jawbone of Azikhantropus",
        cene_f1l: "Age:",
        cene_f1v: "350,000–400,000 years",
        cene_f2l: "Found at:",
        cene_f2v: "Azykh Cave, Gazakh",
        cene_f3l: "Type:",
        cene_f3v: "Pre-Neanderthal",
        cene_desc: "Discovered in 1968 by Mammadali Huseynov, this jawbone changed world anthropology. It is the fourth-oldest human fossil ever found.",
        cene_ctxh: "Anthropological Significance",
        cene_ctxp: "This find confirms that Azerbaijan was one of the earliest cradles where humanity took shape.",
        taglar_tag: "Paleolithic Tools",
        taglar_title: "Taglar Cave Tools",
        taglar_f1l: "Period:",
        taglar_f1v: "Middle Paleolithic (Mousterian culture)",
        taglar_f2l: "Material:",
        taglar_f2v: "Flint",
        taglar_f3l: "Location:",
        taglar_f3v: "Taglar Cave, Fuzuli district",
        taglar_desc: "Taglar Cave is the most important Paleolithic site found in Karabakh after Azykh. The flint tools found here — scrapers, cutters, points — show the hunting and processing techniques of Neanderthal humans.",
        taglar_ctxh: "Mousterian Culture",
        taglar_ctxp: "These tools prove that the generation following Azikhantropus — the classic Neanderthal — settled in Karabakh.",
        damcili_tag: "Mesolithic Period",
        damcili_title: "Damjili Cave Finds",
        damcili_f1l: "Period:",
        damcili_f1v: "Mesolithic (10,000–8,000 BC)",
        damcili_f2l: "Material:",
        damcili_f2v: "Bone, stone",
        damcili_f3l: "Location:",
        damcili_f3v: "Damjili Cave, Gazakh district",
        damcili_desc: "The microlithic tools and bone implements found in Damjili Cave reflect the gradual transition from hunting to agriculture and animal husbandry during the Mesolithic period.",
        damcili_ctxh: "A Transitional Era",
        damcili_ctxp: "The Damjili finds signal the first steps on Azerbaijan's path toward the \"Neolithic Revolution.\"",
        azixfauna_tag: "Paleozoology",
        azixfauna_title: "Faunal Remains of Azykh Cave",
        azixfauna_f1l: "Period:",
        azixfauna_f1v: "400,000–350,000 years ago",
        azixfauna_f2l: "Material:",
        azixfauna_f2v: "Bone remains",
        azixfauna_f3l: "Location:",
        azixfauna_f3v: "Azykh Cave, Fuzuli district",
        azixfauna_desc: "Found in the same layers as Azikhantropus, the bones of cave bears, bison and deer show which animals ancient humans hunted and how they used the cave.",
        azixfauna_ctxh: "An Ecological Witness",
        azixfauna_ctxp: "These remains give science invaluable data about Karabakh's climate and wildlife 400,000 years ago.",
        sikke_tag: "Numismatics",
        sikke_title: "Ancient Azerbaijani Coin",
        sikke_f1l: "Period:",
        sikke_f1v: "7th–10th centuries",
        sikke_f2l: "Material:",
        sikke_f2v: "Silver dirham",
        sikke_f3l: "Weight:",
        sikke_f3v: "~2.8 g",
        sikke_desc: "This coin demonstrates the economic independence of medieval states on Azerbaijani soil. The Kufic inscription bears the name of the ruling caliph of the era.",
        sikke_ctxh: "Why It Matters",
        sikke_ctxp: "Minting coins was a symbol of statehood. This artifact gives insight into the era's trade system.",
        dulus_tag: "Archaeology",
        dulus_title: "Ordubad Bronze Artifact",
        dulus_f1l: "Location:",
        dulus_f1v: "Nakhchivan AR",
        dulus_f2l: "Period:",
        dulus_f2v: "Bronze Age (2nd mill. BC)",
        dulus_f3l: "Culture:",
        dulus_f3v: "Painted Ware culture",
        dulus_desc: "Found during excavations near Ordubad, this artifact shows the high craftsmanship of the ancient Nakhchivan tribes.",
        dulus_ctxh: "A Region's History",
        dulus_ctxp: "Nakhchivan is considered one of the oldest centers of Azerbaijani statehood.",
        sasani_tag: "Numismatics",
        sasani_title: "Sasanian Dirham",
        sasani_f1l: "Period:",
        sasani_f1v: "6th century (Sasanian Empire)",
        sasani_f2l: "Material:",
        sasani_f2v: "Silver",
        sasani_f3l: "Location:",
        sasani_f3v: "Azerbaijani territory (a Sasanian province)",
        sasani_desc: "Reflecting pre-Islamic currency, this dirham was struck with the portrait of a Sasanian shahanshah and a fire-altar symbol. It shows that Azerbaijan was a province of the Sasanian Empire before the Arab conquest.",
        sasani_ctxh: "Predecessor Coin",
        sasani_ctxp: "The weight and shape standard of later Arab dirhams was taken directly from these Sasanian coins.",
        shirvansikke_tag: "Numismatics",
        shirvansikke_title: "Shirvanshah Coin",
        shirvansikke_f1l: "Period:",
        shirvansikke_f1v: "12th–15th centuries",
        shirvansikke_f2l: "Material:",
        shirvansikke_f2v: "Silver/copper",
        shirvansikke_f3l: "Location:",
        shirvansikke_f3v: "Shamakhi, Baku (Shirvanshah state)",
        shirvansikke_desc: "Struck by the Shirvanshah dynasty, these coins bear the ruler's name and the era's declaration of faith. They are economic evidence of a state that lasted roughly 800 years.",
        shirvansikke_ctxh: "A Long-Lived Dynasty",
        shirvansikke_ctxp: "The Shirvanshahs were the longest-ruling dynasty in Azerbaijani history, and these coins carry traces from every one of their eras.",
        eldeniz_tag: "Numismatics",
        eldeniz_title: "Eldiguzid-Era Coin",
        eldeniz_f1l: "Period:",
        eldeniz_f1v: "12th century",
        eldeniz_f2l: "Material:",
        eldeniz_f2v: "Copper (fals)",
        eldeniz_f3l: "Location:",
        eldeniz_f3v: "Ganja, Nakhchivan (Atabeg state)",
        eldeniz_desc: "Struck by the Azerbaijani Atabeg (Eldiguzid) state, this coin is a piece of the economic life of the era in which Nizami Ganjavi lived. It is decorated with geometric patterns continuing Seljuk traditions.",
        eldeniz_ctxh: "A Literary Golden Age",
        eldeniz_ctxp: "At the time this coin was struck, Nizami Ganjavi was writing his works in Ganja — the Momine Khatun Mausoleum in Hall 4 belongs to this very era.",
        at_tag: "Archaeology",
        at_title: "Ancient Horse Figurine",
        at_f1l: "Period:",
        at_f1v: "1st millennium BC",
        at_f2l: "Material:",
        at_f2v: "Bronze",
        at_f3l: "Location:",
        at_f3v: "Mil-Karabakh plain",
        at_desc: "A bronze horse figurine from antiquity. The horse was a symbol of power and freedom in ancient Azerbaijani culture.",
        at_ctxh: "Symbolic Meaning",
        at_ctxp: "Horse figurines are often found in rulers' tombs — symbolizing the soul riding into the afterlife.",
        bicak_tag: "Bronze Age",
        bicak_title: "Bronze Age Weapons",
        bicak_f1l: "Period:",
        bicak_f1v: "2nd–1st millennium BC",
        bicak_f2l: "Material:",
        bicak_f2v: "Bronze",
        bicak_f3l: "Location:",
        bicak_f3v: "Ganja-Gazakh region",
        bicak_desc: "This set — a dagger, a spearhead and an arrowhead — was used for combat and hunting.",
        bicak_ctxh: "Craftsmanship",
        bicak_ctxp: "The form of these weapons shows the unique development of the Near Eastern warfare tradition in Azerbaijan.",
        manna_tag: "Manna Kingdom",
        manna_title: "Manna-Era Gold Objects",
        manna_f1l: "Period:",
        manna_f1v: "9th–7th century BC",
        manna_f2l: "Material:",
        manna_f2v: "Gold",
        manna_f3l: "Location:",
        manna_f3v: "Southern Azerbaijan",
        manna_desc: "This set of gold ornaments — a necklace, bracelets, earrings — bears witness to the refined craftsmanship of the Manna kingdom.",
        manna_ctxh: "Statehood",
        manna_ctxp: "Manna is one of the oldest states of Azerbaijan, known from Assyrian sources.",
        gamigaya_tag: "Petroglyphs",
        gamigaya_title: "Gamigaya Petroglyphs",
        gamigaya_f1l: "Period:",
        gamigaya_f1v: "4th–1st millennium BC",
        gamigaya_f2l: "Location:",
        gamigaya_f2v: "Ordubad, Nakhchivan",
        gamigaya_f3l: "Type:",
        gamigaya_f3v: "Rock carvings",
        gamigaya_desc: "Thousands of ancient rock carvings have been found in the Gamigaya mountains, depicting animals, humans and astral symbols.",
        gamigaya_ctxh: "Scientific Significance",
        gamigaya_ctxp: "The Gamigaya carvings are a rare source reflecting the worldview and economic life of ancient peoples.",
        qobustan_tag: "Petroglyphs",
        qobustan_title: "Gobustan Rock Art",
        qobustan_f1l: "Period:",
        qobustan_f1v: "Paleolithic – Medieval",
        qobustan_f2l: "Location:",
        qobustan_f2v: "Gobustan National Park",
        qobustan_f3l: "Count:",
        qobustan_f3v: "6,000+ carvings",
        qobustan_desc: "Thousands-of-years-old rock carvings in Gobustan National Park depict hunting scenes, dancing figures and boats.",
        qobustan_ctxh: "UNESCO Heritage",
        qobustan_ctxp: "Gobustan was inscribed on the UNESCO World Heritage List in 2007.",
        xinisli_tag: "Archaeology",
        xinisli_title: "Khinisli Necropolis",
        xinisli_f1l: "Period:",
        xinisli_f1v: "8th–4th century BC",
        xinisli_f2l: "Location:",
        xinisli_f2v: "Khinisli, near Baku",
        xinisli_f3l: "Type:",
        xinisli_f3v: "Scythian-era necropolis",
        xinisli_desc: "Excavations at the Khinisli necropolis uncovered gold ornaments, weapons, horse gear and ceramics.",
        xinisli_ctxh: "Historical Context",
        xinisli_ctxp: "The Khinisli necropolis is one of the richest archaeological sources for the pre-Albanian era.",
        mingecevir_tag: "Albanian Era",
        mingecevir_title: "Finds from the Mingachevir Necropolis",
        mingecevir_f1l: "Period:",
        mingecevir_f1v: "1st century BC – 8th century AD",
        mingecevir_f2l: "Location:",
        mingecevir_f2v: "Mingachevir, Kura riverbank",
        mingecevir_f3l: "Find type:",
        mingecevir_f3v: "Jar burials, ceramics, jewelry",
        mingecevir_desc: "Excavations at the Mingachevir necropolis uncovered the richest archaeological material of Caucasian Albania.",
        mingecevir_ctxh: "Archaeological Significance",
        mingecevir_ctxp: "The Mingachevir finds prove the cultural diversity of Caucasian Albania.",
        skif_tag: "Scythian Era",
        skif_title: "Scythian Kurgan Finds",
        skif_f1l: "Period:",
        skif_f1v: "7th–4th century BC",
        skif_f2l: "Location:",
        skif_f2v: "Mil plain, Aghjabadi",
        skif_f3l: "Material:",
        skif_f3v: "Gold, bronze, iron",
        skif_desc: "Gold ornaments recovered from Scythian kurgans on the Mil plain prove the presence of Scythian tribes on Azerbaijani soil.",
        skif_ctxh: "Historical Context",
        skif_ctxp: "The Scythians were a nomadic people who arrived in the South Caucasus in the 7th century BC.",
        qala_tag: "Medieval Period",
        qala_title: "Gala Archaeological-Ethnographic Complex",
        qala_f1l: "Period:",
        qala_f1v: "Early Middle Ages – 19th century",
        qala_f2l: "Location:",
        qala_f2v: "Gala village, Absheron",
        qala_f3l: "Status:",
        qala_f3v: "State Museum Reserve",
        qala_desc: "Excavations at Gala village on the Absheron peninsula uncovered more than 2,000 artifacts.",
        qala_ctxh: "Cultural Heritage",
        qala_ctxp: "The Gala complex is a rare museum reserve preserving Absheron's archaeological, ethnographic and architectural heritage together.",
        shirvan_tag: "Medieval Period",
        shirvan_title: "Shirvanshahs' Palace",
        shirvan_f1l: "Period:",
        shirvan_f1v: "15th century",
        shirvan_f2l: "Location:",
        shirvan_f2v: "Icherisheher, Baku",
        shirvan_f3l: "Status:",
        shirvan_f3v: "UNESCO monument",
        shirvan_desc: "The Shirvanshahs' Palace is a gem of Azerbaijani architecture. The complex includes a palace, a mosque, a mausoleum and a bathhouse.",
        shirvan_ctxh: "Architectural Heritage",
        shirvan_ctxp: "The complex was inscribed on the UNESCO World Heritage List in 2000.",
        qizqalasi_tag: "Architectural Monument",
        qizqalasi_title: "Maiden Tower",
        qizqalasi_f1l: "Period:",
        qizqalasi_f1v: "12th century (lower layers older)",
        qizqalasi_f2l: "Location:",
        qizqalasi_f2v: "Icherisheher, Baku",
        qizqalasi_f3l: "Status:",
        qizqalasi_f3v: "UNESCO World Heritage",
        qizqalasi_desc: "The Maiden Tower is Azerbaijan's most recognized symbol — an 8-story, cylindrical fortress 29 meters tall. Debate continues over its construction date and purpose: some researchers consider it a defensive fort, others a Zoroastrian temple. Several legends surround its name — the most famous tells of a princess who threw herself into the Caspian from the tower to escape a forced marriage arranged by her father.",
        qizqalasi_ctxh: "An Architectural Mystery",
        qizqalasi_ctxp: "The purpose of the mysterious projection on the tower's wall and its unusual thickness has never been fully explained — making it one of the most enigmatic monuments of the East.",
        sheki_tag: "Palace Architecture",
        sheki_title: "Sheki Khans' Palace",
        sheki_f1l: "Period:",
        sheki_f1v: "18th century",
        sheki_f2l: "Location:",
        sheki_f2v: "City of Sheki",
        sheki_f3l: "Feature:",
        sheki_f3v: "Shebeke lattice windows, wall paintings",
        sheki_desc: "Built as the summer residence of the Sheki khans, this palace was assembled without a single nail — the wooden pieces are joined only by carving and interlocking. The shebeke lattice windows are made from fragments of colored glass; when sunlight hits them, the room is bathed in a thousand colors. The wall frescoes are rich with hunting scenes and floral patterns.",
        sheki_ctxh: "A Craftsmanship Marvel",
        sheki_ctxp: "Making a single shebeke window took craftsmen months — a technique that is nearly forgotten today.",
        momune_tag: "Mausoleum Architecture",
        momune_title: "Momine Khatun Mausoleum",
        momune_f1l: "Period:",
        momune_f1v: "1186",
        momune_f2l: "Architect:",
        momune_f2v: "Ajami Nakhchivani",
        momune_f3l: "Location:",
        momune_f3v: "City of Nakhchivan",
        momune_desc: "The greatest work of Ajami Abubakr oglu Nakhchivani, founder of the Nakhchivan school of architecture. This ten-sided prism-shaped mausoleum, covered in geometric and epigraphic patterns, is considered the pinnacle of Eastern architecture. It was built in memory of Momine Khatun, wife of Atabeg Shamsaddin Eldeniz.",
        momune_ctxh: "The Nakhchivan School of Architecture",
        momune_ctxp: "The geometric ornamentation techniques Ajami used went on to influence Near Eastern architecture for centuries.",
        ateshgah_tag: "Zoroastrian Shrine",
        ateshgah_title: "Ateshgah Fire Temple",
        ateshgah_f1l: "Period:",
        ateshgah_f1v: "17th–18th centuries",
        ateshgah_f2l: "Location:",
        ateshgah_f2v: "Surakhani, Baku",
        ateshgah_f3l: "Built by:",
        ateshgah_f3v: "Indian traders",
        ateshgah_desc: "Natural gas escaping from the earth burned here for centuries without going out, turning this site into a sacred shrine. The central temple, inside pentagonal fortress walls, was built by Indian traders and served as a shared place of worship for Zoroastrians, Hindus and Sikhs. Inscriptions in Sanskrit and Punjabi remain on its walls.",
        ateshgah_ctxh: "The Undying Flame",
        ateshgah_ctxp: "When the oil and gas industry developed in the 20th century, the natural gas was depleted, and today the \"eternal flame\" is sustained by piped gas.",
        gencegapilari_tag: "Bronze Casting Art",
        gencegapilari_title: "Gates of Ganja",
        gencegapilari_f1l: "Made:",
        gencegapilari_f1v: "1063",
        gencegapilari_f2l: "Material:",
        gencegapilari_f2v: "Bronze",
        gencegapilari_f3l: "Current location:",
        gencegapilari_f3v: "Gelati Monastery, Georgia",
        gencegapilari_desc: "Cast for the gates of the city of Ganja, these magnificent bronze doors are a rare example of medieval metal-casting art. After a powerful earthquake destroyed the city in 1139, and later when Russian troops seized Ganja in 1804, the gates were carried off as spoils and are kept to this day at Gelati Monastery in Georgia.",
        gencegapilari_ctxh: "Unreturned Heritage",
        gencegapilari_ctxp: "Arabic inscriptions on the gates precisely confirm they were made in Ganja — one of the most striking examples of lost cultural heritage.",
        footer_credit: "Created by Mahammad Huseynov",
        footer_home: "Back to Home",
        hall_word: "HALL",
        pause: "Pause",
        auth_btn: "Log in",
        auth_wait: "Please wait...",
        auth_signup_ok: "✅ Signed up! Check your email and click the link.",
        err_invalid: "❌ Incorrect email or password",
        err_unconfirmed: "❌ Please confirm your email first",
        err_exists: "❌ This email is already registered",
        err_password: "❌ Password must be at least 6 characters",
        badge_gem: "★ Hall Highlight",
        badge_flagship: "★ Flagship Exhibit",
        badge_symbol: "★ National Symbol",
        count_exhibit: "exhibits",
        count_finds: "finds",
        count_monuments: "monuments",
        count_events: "events",
        comments_title: "Comments",
        comment_placeholder: "Write your thoughts...",
        comment_send: "Send",
        comments_loading: "Loading comments...",
        comments_empty: "No comments yet. Be the first to write one!",
        comments_error: "Could not load comments.",
        comment_login_alert: "Please log in first to write a comment!",
        comment_confirm_delete: "Are you sure you want to delete this comment?",
        comment_send_fail: "Could not send comment: ",
        user_default: "User",
    },
    ru: {
        nav_home: "Главная",
        nav_about: "О нас",
        nav_lobby: "Лобби музея",
        nav_timeline: "Хронология",
        back_to_lobby: "Назад в лобби",
        music: "Музыка",

        auth_login_title: "Войти",
        auth_signup_title: "Регистрация",
        auth_sub: "Добро пожаловать в AzerHistory 3D",
        auth_email: "Email",
        auth_password: "Пароль",
        auth_login_btn: "Войти",
        auth_signup_btn: "Зарегистрироваться",
        auth_toggle_to_signup: "Нет аккаунта? Зарегистрируйтесь",
        auth_fullname: "Имя и фамилия",
        auth_country: "Страна",
        auth_toggle_to_login: "Уже есть аккаунт? Войти",

        hero_badge: "🏛️ Цифровой Музей",
        hero_title1: "Цифровой Архив",
        hero_title2: "Национального Наследия",
        hero_sub: "Откройте для себя тысячелетнее наследие с помощью современных технологий. Каждый артефакт — окно в прошлое нашего народа.",
        hero_btn: "Войти в Музей",
        hero_btn2: "Хронология",
        stat1: "Экспонатов",
        stat2: "Лет Истории",
        stat3: "3D Модели",
        scroll: "Прокрутите вниз",

        about_eyebrow: "| О НАС",
        about_title: "Что такое AzerHistory 3D?",
        about_p1: "AzerHistory 3D — это онлайн-музей, переносящий тысячелетнюю историю Азербайджана в цифровой мир. Вместо чтения книги вы можете увидеть каждый артефакт своими глазами, вращать монеты и древние предметы на 360°, детально рассмотреть исторические памятники.",
        about_p2: "Наш музей состоит из пяти отдельных залов — каждый несёт свою эпоху и свою историю: от первых следов человечества до золотого мастерства древних государств и архитектурных чудес, высеченных в камне. Хронология проведёт вас через путь от 400 000 лет назад до наших дней.",
        about_p3: "Зарегистрируйтесь, чтобы оставлять свои мысли к каждому экспонату и читать комментарии других. Наша цель проста: заставить прошлое говорить на языке сегодняшнего дня.",
        about_btn: "Исследовать Музей",
        about_stat1: "Залов Музея",
        about_stat2: "Экспонатов",
        about_stat3: "Лет Истории",
        about_stat4: "3D Модели",

        lobby_badge: "🏛️ Цифровой Музей — Главное Лобби",
        lobby_h1_1: "Добро пожаловать.",
        lobby_h1_2: "С какого зала начнём?",
        lobby_p: "Каждый зал несёт свою эпоху, свою историю. Начните с любого зала и возвращайтесь в это лобби в любое время.",
        hall1_title: "Палеонтология",
        hall1_desc: "Первые следы человечества — путь длиной в 400 000 лет.",
        hall2_title: "Нумизматика и 3D Архив",
        hall2_desc: "Монеты, керамика — предметы, которые можно держать в руках и вращать на 360°.",
        hall3_title: "Археологические Находки",
        hall3_desc: "Золотые украшения, оружие, наскальные рисунки — поднятое из глубин земли.",
        hall4_title: "Архитектурные Памятники",
        hall4_desc: "Девичья башня, дворец в Шеки, Атешгях — наша история, высеченная в камне.",
        hall5_title: "Хронология",
        hall5_desc: "От 400 000 лет назад до наших дней — вся история на одном пути.",
        eksponat_word: "экспонатов",

        hall1_page_title1: "Зал",
        hall1_page_title2: "Палеонтологии",
        hall1_page_sub: "Древнейшие следы человечества на земле Азербайджана — история окаменевших костей.",
        hall2_page_title1: "Нумизматика",
        hall2_page_title2: "и 3D Архив",
        hall2_page_sub: "Предметы, которые можно держать в руках и вращать на 360° — монеты и сосуды тысячелетней давности.",
        hall3_page_title1: "Археологические",
        hall3_page_title2: "Находки",
        hall3_page_sub: "Золотые украшения, оружие и наскальные рисунки, поднятые из глубин земли — путешествие длиной в девять тысяч лет.",
        hall4_page_title1: "Архитектурные",
        hall4_page_title2: "Памятники",
        hall4_page_sub: "История, высеченная в камне, дереве и бронзе — дворцы, мавзолеи, крепости и храмы.",

        footer_copy: "© 2026 AzerHistory 3D",
        cene_tag: "Палеоантропология",
        cene_title: "Челюстная кость Азыхантропа",
        cene_f1l: "Возраст:",
        cene_f1v: "350 000–400 000 лет",
        cene_f2l: "Место находки:",
        cene_f2v: "Азыхская пещера, Газах",
        cene_f3l: "Тип:",
        cene_f3v: "Пре-неандерталец",
        cene_desc: "Обнаруженная в 1968 году Мамедали Гусейновым, эта челюстная кость изменила мировую антропологию. Это четвёртая по древности человеческая окаменелость в мире.",
        cene_ctxh: "Антропологическое значение",
        cene_ctxp: "Эта находка подтверждает, что Азербайджан был одной из древнейших колыбелей формирования человечества.",
        taglar_tag: "Палеолитические орудия",
        taglar_title: "Орудия пещеры Таглар",
        taglar_f1l: "Период:",
        taglar_f1v: "Средний палеолит (мустьерская культура)",
        taglar_f2l: "Материал:",
        taglar_f2v: "Кремень",
        taglar_f3l: "Место:",
        taglar_f3v: "Пещера Таглар, Физулинский район",
        taglar_desc: "Пещера Таглар — важнейшая палеолитическая стоянка, обнаруженная в Карабахе после Азыха. Найденные здесь кремнёвые орудия — скребки, резцы, наконечники — демонстрируют технику охоты и обработки неандертальского человека.",
        taglar_ctxh: "Мустьерская культура",
        taglar_ctxp: "Эти орудия доказывают, что поколение, следующее за Азыхантропом — классический неандерталец — заселило Карабах.",
        damcili_tag: "Мезолитическая эпоха",
        damcili_title: "Находки пещеры Дамджилы",
        damcili_f1l: "Период:",
        damcili_f1v: "Мезолит (X–VIII тыс. до н.э.)",
        damcili_f2l: "Материал:",
        damcili_f2v: "Кость, камень",
        damcili_f3l: "Место:",
        damcili_f3v: "Пещера Дамджилы, Газахский район",
        damcili_desc: "Микролитические орудия и костяные изделия, найденные в пещере Дамджилы, отражают постепенный переход от охоты к земледелию и скотоводству в мезолитическую эпоху.",
        damcili_ctxh: "Переходная эпоха",
        damcili_ctxp: "Находки Дамджилы свидетельствуют о первых шагах Азербайджана на пути к «неолитической революции».",
        azixfauna_tag: "Палеозоология",
        azixfauna_title: "Фаунистические остатки Азыхской пещеры",
        azixfauna_f1l: "Период:",
        azixfauna_f1v: "400 000–350 000 лет назад",
        azixfauna_f2l: "Материал:",
        azixfauna_f2v: "Костные остатки",
        azixfauna_f3l: "Место:",
        azixfauna_f3v: "Азыхская пещера, Физулинский район",
        azixfauna_desc: "Найденные в тех же слоях, что и Азыхантроп, кости пещерного медведя, бизона и оленя показывают, на каких животных охотился древний человек и как он использовал пещеру.",
        azixfauna_ctxh: "Экологический свидетель",
        azixfauna_ctxp: "Эти остатки дают науке бесценные данные о климате и животном мире Карабаха 400 000 лет назад.",
        sikke_tag: "Нумизматика",
        sikke_title: "Древняя азербайджанская монета",
        sikke_f1l: "Период:",
        sikke_f1v: "VII–X века",
        sikke_f2l: "Материал:",
        sikke_f2v: "Серебряный дирхем",
        sikke_f3l: "Вес:",
        sikke_f3v: "~2,8 г",
        sikke_desc: "Эта монета демонстрирует экономическую независимость средневековых государств на территории Азербайджана. Куфическая надпись содержит имя правящего халифа той эпохи.",
        sikke_ctxh: "Почему это важно",
        sikke_ctxp: "Чеканка монет была символом государственности. Этот артефакт даёт представление о торговой системе той эпохи.",
        dulus_tag: "Археология",
        dulus_title: "Ордубадский бронзовый артефакт",
        dulus_f1l: "Место:",
        dulus_f1v: "Нахчыванская АР",
        dulus_f2l: "Период:",
        dulus_f2v: "Бронзовый век (2-е тыс. до н.э.)",
        dulus_f3l: "Культура:",
        dulus_f3v: "Культура расписной керамики",
        dulus_desc: "Найденный при раскопках близ Ордубада, этот артефакт демонстрирует высокое мастерство древних нахчыванских племён.",
        dulus_ctxh: "История региона",
        dulus_ctxp: "Нахчыван считается одним из древнейших центров азербайджанской государственности.",
        sasani_tag: "Нумизматика",
        sasani_title: "Сасанидский дирхем",
        sasani_f1l: "Период:",
        sasani_f1v: "VI век (Сасанидская империя)",
        sasani_f2l: "Материал:",
        sasani_f2v: "Серебро",
        sasani_f3l: "Место:",
        sasani_f3v: "Территория Азербайджана (сасанидская провинция)",
        sasani_desc: "Отражая доисламскую валюту, этот дирхем отчеканен с портретом сасанидского шахиншаха и символом алтаря огня. Он показывает, что до арабского завоевания Азербайджан был провинцией Сасанидской империи.",
        sasani_ctxh: "Монета-предшественник",
        sasani_ctxp: "Весовой и формовой стандарт последующих арабских дирхемов был заимствован именно с этих сасанидских монет.",
        shirvansikke_tag: "Нумизматика",
        shirvansikke_title: "Монета Ширваншахов",
        shirvansikke_f1l: "Период:",
        shirvansikke_f1v: "XII–XV века",
        shirvansikke_f2l: "Материал:",
        shirvansikke_f2v: "Серебро/медь",
        shirvansikke_f3l: "Место:",
        shirvansikke_f3v: "Шемаха, Баку (государство Ширваншахов)",
        shirvansikke_desc: "Отчеканенные династией Ширваншахов, эти монеты несут имя правителя и символ веры той эпохи. Это экономическое свидетельство государства, просуществовавшего около 800 лет.",
        shirvansikke_ctxh: "Долговечная династия",
        shirvansikke_ctxp: "Ширваншахи были самой долгоправящей династией в истории Азербайджана, и эти монеты несут следы каждой из их эпох.",
        eldeniz_tag: "Нумизматика",
        eldeniz_title: "Монета эпохи Эльдегизидов",
        eldeniz_f1l: "Период:",
        eldeniz_f1v: "XII век",
        eldeniz_f2l: "Материал:",
        eldeniz_f2v: "Медь (фельс)",
        eldeniz_f3l: "Место:",
        eldeniz_f3v: "Гянджа, Нахчыван (государство Атабеков)",
        eldeniz_desc: "Отчеканенная государством азербайджанских Атабеков (Эльдегизидов), эта монета — часть экономической жизни эпохи, в которую жил Низами Гянджеви. Она украшена геометрическими узорами, продолжающими сельджукские традиции.",
        eldeniz_ctxh: "Золотой век литературы",
        eldeniz_ctxp: "Когда чеканили эту монету, Низами Гянджеви писал свои произведения в Гяндже — мавзолей Момине-хатун в Зале 4 принадлежит именно этой эпохе.",
        at_tag: "Археология",
        at_title: "Древняя фигурка коня",
        at_f1l: "Период:",
        at_f1v: "1-е тыс. до н.э.",
        at_f2l: "Материал:",
        at_f2v: "Бронза",
        at_f3l: "Место:",
        at_f3v: "Мильско-Карабахская равнина",
        at_desc: "Бронзовая фигурка коня античной эпохи. Конь был символом силы и свободы в древней азербайджанской культуре.",
        at_ctxh: "Символическое значение",
        at_ctxp: "Фигурки коней часто находят в гробницах правителей — они символизируют душу, отправляющуюся верхом в загробный мир.",
        bicak_tag: "Бронзовый век",
        bicak_title: "Оружие бронзового века",
        bicak_f1l: "Период:",
        bicak_f1v: "2–1-е тыс. до н.э.",
        bicak_f2l: "Материал:",
        bicak_f2v: "Бронза",
        bicak_f3l: "Место:",
        bicak_f3v: "Гянджа-Газахский регион",
        bicak_desc: "Этот набор — кинжал, наконечник копья и наконечник стрелы — использовался для боя и охоты.",
        bicak_ctxh: "Мастерство",
        bicak_ctxp: "Форма этого оружия показывает уникальное развитие ближневосточной военной традиции в Азербайджане.",
        manna_tag: "Государство Манна",
        manna_title: "Золотые предметы эпохи Манны",
        manna_f1l: "Период:",
        manna_f1v: "IX–VII вв. до н.э.",
        manna_f2l: "Материал:",
        manna_f2v: "Золото",
        manna_f3l: "Место:",
        manna_f3v: "Южный Азербайджан",
        manna_desc: "Этот набор золотых украшений — ожерелье, браслеты, серьги — свидетельствует об утончённом мастерстве государства Манна.",
        manna_ctxh: "Государственность",
        manna_ctxp: "Манна — одно из древнейших государств Азербайджана, известное по ассирийским источникам.",
        gamigaya_tag: "Петроглифы",
        gamigaya_title: "Петроглифы Гямигая",
        gamigaya_f1l: "Период:",
        gamigaya_f1v: "IV–I тыс. до н.э.",
        gamigaya_f2l: "Место:",
        gamigaya_f2v: "Ордубад, Нахчыван",
        gamigaya_f3l: "Тип:",
        gamigaya_f3v: "Наскальные рисунки",
        gamigaya_desc: "В горах Гямигая обнаружены тысячи древних наскальных рисунков, изображающих животных, людей и астральные символы.",
        gamigaya_ctxh: "Научное значение",
        gamigaya_ctxp: "Рисунки Гямигая — редкий источник, отражающий мировоззрение и хозяйственную жизнь древних народов.",
        qobustan_tag: "Петроглифы",
        qobustan_title: "Наскальное искусство Гобустана",
        qobustan_f1l: "Период:",
        qobustan_f1v: "Палеолит – Средние века",
        qobustan_f2l: "Место:",
        qobustan_f2v: "Национальный парк Гобустан",
        qobustan_f3l: "Количество:",
        qobustan_f3v: "6000+ рисунков",
        qobustan_desc: "Тысячелетние наскальные рисунки в национальном парке Гобустан изображают сцены охоты, танцующих людей и лодки.",
        qobustan_ctxh: "Наследие ЮНЕСКО",
        qobustan_ctxp: "Гобустан был включён в список Всемирного наследия ЮНЕСКО в 2007 году.",
        xinisli_tag: "Археология",
        xinisli_title: "Некрополь Хыныслы",
        xinisli_f1l: "Период:",
        xinisli_f1v: "VIII–IV вв. до н.э.",
        xinisli_f2l: "Место:",
        xinisli_f2v: "Хыныслы, окрестности Баку",
        xinisli_f3l: "Тип:",
        xinisli_f3v: "Некрополь скифской эпохи",
        xinisli_desc: "Раскопки некрополя Хыныслы выявили золотые украшения, оружие, конское снаряжение и керамику.",
        xinisli_ctxh: "Исторический контекст",
        xinisli_ctxp: "Некрополь Хыныслы — один из богатейших археологических источников доалбанской эпохи.",
        mingecevir_tag: "Албанская эпоха",
        mingecevir_title: "Находки некрополя Мингячевира",
        mingecevir_f1l: "Период:",
        mingecevir_f1v: "I в. до н.э. – VIII в. н.э.",
        mingecevir_f2l: "Место:",
        mingecevir_f2v: "Мингячевир, берег Куры",
        mingecevir_f3l: "Тип находки:",
        mingecevir_f3v: "Кувшинные погребения, керамика, украшения",
        mingecevir_desc: "Раскопки некрополя Мингячевира выявили богатейший археологический материал Кавказской Албании.",
        mingecevir_ctxh: "Археологическое значение",
        mingecevir_ctxp: "Находки Мингячевира доказывают культурное разнообразие Кавказской Албании.",
        skif_tag: "Скифская эпоха",
        skif_title: "Находки скифского кургана",
        skif_f1l: "Период:",
        skif_f1v: "VII–IV вв. до н.э.",
        skif_f2l: "Место:",
        skif_f2v: "Мильская степь, Агджабеди",
        skif_f3l: "Материал:",
        skif_f3v: "Золото, бронза, железо",
        skif_desc: "Золотые украшения, найденные в скифских курганах Мильской степи, доказывают присутствие скифских племён на территории Азербайджана.",
        skif_ctxh: "Исторический контекст",
        skif_ctxp: "Скифы — кочевой народ, пришедший на Южный Кавказ в VII веке до н.э.",
        qala_tag: "Средневековье",
        qala_title: "Археолого-этнографический комплекс Гала",
        qala_f1l: "Период:",
        qala_f1v: "Раннее Средневековье – XIX век",
        qala_f2l: "Место:",
        qala_f2v: "Село Гала, Абшерон",
        qala_f3l: "Статус:",
        qala_f3v: "Государственный музей-заповедник",
        qala_desc: "Раскопки в селе Гала на Абшеронском полуострове выявили более 2000 артефактов.",
        qala_ctxh: "Культурное наследие",
        qala_ctxp: "Комплекс Гала — редкий музей-заповедник, сохраняющий археологическое, этнографическое и архитектурное наследие Абшерона в едином комплексе.",
        shirvan_tag: "Средневековье",
        shirvan_title: "Дворец Ширваншахов",
        shirvan_f1l: "Период:",
        shirvan_f1v: "XV век",
        shirvan_f2l: "Место:",
        shirvan_f2v: "Ичеришехер, Баку",
        shirvan_f3l: "Статус:",
        shirvan_f3v: "Памятник ЮНЕСКО",
        shirvan_desc: "Дворец Ширваншахов — жемчужина азербайджанской архитектуры. В комплекс входят дворец, мечеть, мавзолей и баня.",
        shirvan_ctxh: "Архитектурное наследие",
        shirvan_ctxp: "Комплекс был включён в список Всемирного наследия ЮНЕСКО в 2000 году.",
        qizqalasi_tag: "Архитектурный памятник",
        qizqalasi_title: "Девичья башня",
        qizqalasi_f1l: "Период:",
        qizqalasi_f1v: "XII век (нижние слои древнее)",
        qizqalasi_f2l: "Место:",
        qizqalasi_f2v: "Ичеришехер, Баку",
        qizqalasi_f3l: "Статус:",
        qizqalasi_f3v: "Всемирное наследие ЮНЕСКО",
        qizqalasi_desc: "Девичья башня — самый узнаваемый символ Азербайджана: 8-этажная цилиндрическая крепость высотой 29 метров. Споры о дате постройки и назначении башни продолжаются до сих пор: одни исследователи считают её оборонительным укреплением, другие — зороастрийским храмом. С её названием связано несколько легенд — самая известная рассказывает о царевне, которая бросилась с башни в Каспий, чтобы избежать насильного брака, устроенного её отцом.",
        qizqalasi_ctxh: "Архитектурная загадка",
        qizqalasi_ctxp: "Назначение загадочного выступа на стене башни и необычная толщина стен до сих пор не получили полного объяснения — это делает её одним из самых загадочных памятников Востока.",
        sheki_tag: "Дворцовая архитектура",
        sheki_title: "Дворец шекинских ханов",
        sheki_f1l: "Период:",
        sheki_f1v: "XVIII век",
        sheki_f2l: "Место:",
        sheki_f2v: "Город Шеки",
        sheki_f3l: "Особенность:",
        sheki_f3v: "Окна-шебеке, настенная живопись",
        sheki_desc: "Построенный как летняя резиденция шекинских ханов, этот дворец собран без единого гвоздя — деревянные детали соединены только резьбой и врезкой. Окна-шебеке сделаны из фрагментов цветного стекла; когда на них падает солнечный свет, комната окрашивается в тысячу цветов. Настенные фрески богаты сценами охоты и цветочными узорами.",
        sheki_ctxh: "Чудо мастерства",
        sheki_ctxp: "Изготовление одного окна-шебеке занимало у мастеров месяцы — эта техника сегодня почти забыта.",
        momune_tag: "Мавзолейная архитектура",
        momune_title: "Мавзолей Момине-хатун",
        momune_f1l: "Период:",
        momune_f1v: "1186 год",
        momune_f2l: "Архитектор:",
        momune_f2v: "Аджеми Нахчывани",
        momune_f3l: "Место:",
        momune_f3v: "Город Нахчыван",
        momune_desc: "Величайшее творение Аджеми Абубекр оглы Нахчывани, основателя нахчыванской архитектурной школы. Этот десятигранный мавзолей призматической формы, покрытый геометрическими и эпиграфическими узорами, считается вершиной восточной архитектуры. Построен в память о Момине-хатун, жене атабека Шамседдина Эльдегиза.",
        momune_ctxh: "Нахчыванская архитектурная школа",
        momune_ctxp: "Техники геометрического орнамента, использованные Аджеми, на века повлияли на архитектуру Ближнего Востока.",
        ateshgah_tag: "Зороастрийское святилище",
        ateshgah_title: "Храм огня Атешгях",
        ateshgah_f1l: "Период:",
        ateshgah_f1v: "XVII–XVIII века",
        ateshgah_f2l: "Место:",
        ateshgah_f2v: "Сураханы, Баку",
        ateshgah_f3l: "Основано:",
        ateshgah_f3v: "Индийские торговцы",
        ateshgah_desc: "Природный газ, выходящий из-под земли, горел здесь веками не угасая, что превратило это место в священное святилище. Центральный храм внутри пятиугольных крепостных стен построен индийскими торговцами и служил общим местом поклонения для зороастрийцев, индуистов и сикхов. На его стенах сохранились надписи на санскрите и панджаби.",
        ateshgah_ctxh: "Неугасающее пламя",
        ateshgah_ctxp: "Когда в XX веке развилась нефтегазовая промышленность, природный газ иссяк, и сегодня «вечный огонь» поддерживается подведённым газом.",
        gencegapilari_tag: "Искусство бронзового литья",
        gencegapilari_title: "Гянджинские ворота",
        gencegapilari_f1l: "Изготовлено:",
        gencegapilari_f1v: "1063 год",
        gencegapilari_f2l: "Материал:",
        gencegapilari_f2v: "Бронза",
        gencegapilari_f3l: "Текущее место:",
        gencegapilari_f3v: "Монастырь Гелати, Грузия",
        gencegapilari_desc: "Отлитые для городских ворот Гянджи, эти великолепные бронзовые двери — редкий образец средневекового искусства литья металла. После того как мощное землетрясение разрушило город в 1139 году, а затем в 1804 году русские войска захватили Гянджу, ворота были вывезены как трофей и по сей день хранятся в монастыре Гелати в Грузии.",
        gencegapilari_ctxh: "Невозвращённое наследие",
        gencegapilari_ctxp: "Арабские надписи на воротах точно подтверждают, что они были изготовлены в Гяндже — один из самых ярких примеров утраченного культурного наследия.",
        footer_credit: "Создано Мамедом Гусейновым",
        footer_home: "На главную",
        hall_word: "ЗАЛ",
        pause: "Пауза",
        auth_btn: "Войти",
        auth_wait: "Подождите...",
        auth_signup_ok: "✅ Регистрация прошла успешно! Проверьте почту и перейдите по ссылке.",
        err_invalid: "❌ Неверный email или пароль",
        err_unconfirmed: "❌ Пожалуйста, подтвердите ваш email",
        err_exists: "❌ Этот email уже зарегистрирован",
        err_password: "❌ Пароль должен содержать минимум 6 символов",
        badge_gem: "★ Жемчужина Зала",
        badge_flagship: "★ Флагманский Экспонат",
        badge_symbol: "★ Национальный Символ",
        count_exhibit: "экспонатов",
        count_finds: "находок",
        count_monuments: "памятников",
        count_events: "событий",
        comments_title: "Комментарии",
        comment_placeholder: "Напишите своё мнение...",
        comment_send: "Отправить",
        comments_loading: "Загрузка комментариев...",
        comments_empty: "Комментариев пока нет. Напишите первый!",
        comments_error: "Не удалось загрузить комментарии.",
        comment_login_alert: "Сначала войдите, чтобы написать комментарий!",
        comment_confirm_delete: "Вы уверены, что хотите удалить комментарий?",
        comment_send_fail: "Не удалось отправить комментарий: ",
        user_default: "Пользователь",
    },
};

function tr(key, fallback) {
    const lang = localStorage.getItem("azerhistory_lang") || "az";
    return (T[lang] && T[lang][key]) || (T.az && T.az[key]) || fallback || key;
}

function applySiteLang(lang) {
    const t = T[lang];
    if (!t) return;
    document.querySelectorAll("[data-i18n]").forEach((el) => {
        const key = el.dataset.i18n;
        if (t[key] !== undefined) el.textContent = t[key];
    });
    // Şərh bloku (bütün eksponatlarda təkrarlanır)
    document.querySelectorAll(".comments-title").forEach((el) => (el.textContent = "💬 " + t.comments_title));
    document.querySelectorAll(".comment-input").forEach((el) => (el.placeholder = t.comment_placeholder));
    document.querySelectorAll(".comment-send-btn").forEach((el) => (el.textContent = t.comment_send));

    document.documentElement.lang = lang;
    document.documentElement.dataset.lang = lang;
    document.querySelectorAll(".lang-btn").forEach((btn) => {
        btn.classList.toggle("active", btn.dataset.lang === lang);
    });
    localStorage.setItem("azerhistory_lang", lang);
    window.dispatchEvent(new CustomEvent("langchange", { detail: lang }));
}

document.querySelectorAll(".lang-btn").forEach((btn) => {
    btn.addEventListener("click", () => applySiteLang(btn.dataset.lang));
});

applySiteLang(localStorage.getItem("azerhistory_lang") || "az");
